### PR TITLE
types(Trans): add typechecking on `context` prop

### LINKED ISSUE #1730: `context` values resolved differently (and incorrectly) between `<Trans />` and `t(...)`
## 🐛 Bug Report

`<Trans />` and `t(...)` don't throw the same type errors when used with different context edge cases. But besides being inconsistent both `<Trans />` and `t(...)` don't correctly interfere if the context is ok or not.

## To Reproduce

https://stackblitz.com/edit/vitejs-vite-pabdwy?file=src%2FApp.tsx&terminal=dev

```json
{
  "testContext1": "EN: {{context}}",
  "testContext1_Test1": "EN: Context1 Test1",
  "testContext1_Test2": "EN: Context1 Test2",
  "testContext2_Test1": "EN: Context2 Test1",
  "testContext2_Test2": "EN: Context2 Test2"
}
```

```tsx
// WRONG: type error but SHOULD work
// Type '{ context: "asdf"; }' is not assignable to type 'string'
{t('testContext1', { context: 'asdf' })}
// OK: works
<Trans t={t} i18nKey="testContext1" context={'asdf'} />
// OK: works
<Trans t={t} i18nKey="testContext1" values={{ context: 'asdf' }} />

// OK: type error
// Type '{ context: "asdf"; }' is not assignable to type 'string'
{t('testContext2', { context: 'asdf' })}
// OK: type error
// Type '"testContext2"' is not assignable to type '"testContext2_Test1" | ...
<Trans t={t} i18nKey="testContext2" context={'asdf'} />
// OK: type error
// Type '"testContext2"' is not assignable to type '"testContext2_Test1" | ...
<Trans t={t} i18nKey="testContext2" values={{ context: 'asdf' }} />

// OK: works
{t('testContext2', { context: 'Test1' })}
// WRONG: type error but SHOULD work
// Type '"testContext2"' is not assignable to type '"testContext2_Test1" | ...
<Trans t={t} i18nKey="testContext2" context={'Test1'} />
// WRONG: type error but SHOULD work
// Type '"testContext2"' is not assignable to type '"testContext2_Test1" | ...
<Trans t={t} i18nKey="testContext2" values={{ context: 'Test1' }} />
```

## Expected behavior

See output above.

### PR DESCRIPTION
**Pull request by marcalexiei**
fixes #1730.

This is technically a breaking change since it change `Trans` and `TransProps` type parameters, however I don't think usually people explicit them when using the component... but who knows 🤷.

-----

I tried to replicate a type parameter structure similar to the `TFunction`, 
however, looks like that using a single `TOpt` type parameter doesn't pass the property values (like `context`) down to `TransProps` properly so `ParseKeys` is not aware of the context value.

The only alternative is to add a new type parameter and pass it down the chain, which is basically what @stefan-schweiger proposed in the above linked issue (Thanks 🙏). 

----

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by stefan-schweiger** [comment]
Already did a short look when I saw the PR and from my side every thing seems in order

**Comment by adrai** [comment]
ok, will merge and release in the next hour(s)

**Comment by adrai** [comment]
thank you both... it's included in v14.1.0

File: TransWithoutContext.d.ts [hunk 1]
```diff
@@ -7,14 +7,15 @@ type TransChild = React.ReactNode | Record<string, unknown>;
 export type TransProps<
   Key extends ParseKeys<Ns, TOpt, KPrefix>,
   Ns extends Namespace = _DefaultNamespace,
-  TOpt extends TOptions = {},
   KPrefix = undefined,
+  TContext extends string | undefined = undefined,
+  TOpt extends TOptions & { context?: TContext } = { context: TContext },
```
Comment (natoehv) [inline TransWithoutContext.d.ts:12]: I know this was closed, but if we remove the `{ context: TContext }` it works a pretty better,  like:
`TOpt extends TOptions & { context?: TContext }` in this way the IDE TS autocomplete works:
without context assignation: 
image
with context assignation:
image

Comment (stefan-schweiger) [reply TransWithoutContext.d.ts:12]: Does it still correctly handle the typings for the context `property` of the `Trans` component?

Comment (stefan-schweiger) [reply TransWithoutContext.d.ts:12]: not exactly what I meant :D I meant more something like this:

image
image
